In [1]:
import pandas as pd

# Load dataset & inspect shape
df = pd.read_csv("netflix_titles.csv")
df.shape

(8807, 12)

In [4]:

# Peek at the first and last few rows
df.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [3]:

df.tail(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [5]:
# View data types and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [6]:
# Check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [7]:
# Check for missing values across columns
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [10]:
# Value counts for categorical columns
df["type"].value_counts(dropna=False)

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [9]:
df["rating"].value_counts(dropna=False)

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NaN            4
NC-17          3
UR             3
66 min         1
74 min         1
84 min         1
Name: count, dtype: int64

In [11]:
# Isolate shifted duration values in the rating column
shifted_rows = df[df["rating"].isin(["74 min", "84 min", "66 min"])]
shifted_rows

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [12]:
# Fix misplaced duration values
shift_mask = df["rating"].isin(["74 min", "84 min", "66 min"])
df.loc[shift_mask, "duration"] = df.loc[shift_mask, "rating"]
df.loc[shift_mask, "rating"] = None
df.loc[shift_mask]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,None,74 min,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,None,84 min,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,None,66 min,Movies,The comic puts his trademark hilarious/thought...

In [13]:
# Re-check rating value counts
df["rating"].value_counts(dropna=False)

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NaN            4
NC-17          3
None           3
UR             3
Name: count, dtype: int64

In [14]:
# Group by type and inspect rating distribution
df.groupby("type")["rating"].value_counts()

type     rating
Movie    TV-MA       2062
         TV-14       1427
         R            797
         TV-PG        540
         PG-13        490
         PG           287
         TV-Y7        139
         TV-Y         131
         TV-G         126
         NR            75
         G             41
         TV-Y7-FV       5
         NC-17          3
         UR             3
TV Show  TV-MA       1145
         TV-14        733
         TV-PG        323
         TV-Y7        195
         TV-Y         176
         TV-G          94
         NR             5
         R              2
         TV-Y7-FV       1
Name: count, dtype: int64

In [15]:
#Fill missing rating values with the mode
df["rating"] = df["rating"].fillna(df["rating"].mode()[0])
df["rating"].isna().sum()

np.int64(0)

In [17]:
df[["director", "cast", "country"]].isna().sum()

director    2634
cast         825
country      831
dtype: int64

In [18]:
# Fill missing text values in categorical columns with 'Unknown'
for column in ["director", "cast", "country"]:
    df[column] = df[column].fillna("Unknown")

In [19]:
df[["director", "cast", "country"]].isna().sum()

director    0
cast        0
country     0
dtype: int64

In [22]:
# Check titles missing both director and cast
(df["director"] == "Unknown").sum()

np.int64(2634)

In [21]:
((df["director"] == "Unknown") & (df["cast"] == "Unknown")).sum()

np.int64(352)

In [23]:
# Strip white space and convert 'date_added' to datetime
df["date_added"] = df["date_added"].str.strip()

In [24]:
df["date_added"] = pd.to_datetime(df["date_added"], format="%B %d, %Y")

In [25]:
df["date_added"].head()

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-24
4   2021-09-24
Name: date_added, dtype: datetime64[ns]

In [26]:
# Check missing dates and inspect affected rows
df["date_added"].isna().sum()

np.int64(10)

In [27]:
df[df["date_added"].isna()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6066,s6067,TV Show,A Young Doctor's Notebook and Other Stories,Unknown,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaT,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6174,s6175,TV Show,Anthony Bourdain: Parts Unknown,Unknown,Anthony Bourdain,United States,NaT,2018,TV-PG,5 Seasons,Docuseries,This CNN original series has chef Anthony Bour...
6795,s6796,TV Show,Frasier,Unknown,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,NaT,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies",Frasier Crane is a snooty but lovable Seattle ...
6806,s6807,TV Show,Friends,Unknown,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaT,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...
6901,s6902,TV Show,Gunslinger Girl,Unknown,"Yuuka Nanri, Kanako Mitsuhashi, Eri Sendai, Am...",Japan,NaT,2008,TV-14,2 Seasons,"Anime Series, Crime TV Shows","On the surface, the Social Welfare Agency appe..."
7196,s7197,TV Show,Kikoriki,Unknown,Igor Dmitriev,Unknown,NaT,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
7254,s7255,TV Show,La Familia P. Luche,Unknown,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,NaT,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...","This irreverent sitcom featues Ludovico, Feder..."
7406,s7407,TV Show,Maron,Unknown,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaT,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
7847,s7848,TV Show,Red vs. Blue,Unknown,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaT,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
8182,s8183,TV Show,The Adventures of Figaro Pho,Unknown,"Luke Jurevicius, Craig Behenna, Charlotte Haml...",Australia,NaT,2015,TV-Y7,2 Seasons,"Kids' TV, TV Comedies","Imagine your worst fears, then multiply them: ..."

In [28]:
# Extract year and month features from 'date_added'
df["year_added"] = df["date_added"].dt.year
df["month_added"] = df["date_added"].dt.month

In [29]:
df[["date_added", "year_added", "month_added"]].head()

  date_added  year_added  month_added
0 2021-09-25      2021.0          9.0
1 2021-09-24      2021.0          9.0
2 2021-09-24      2021.0          9.0
3 2021-09-24      2021.0          9.0
4 2021-09-24      2021.0          9.0

In [30]:
# Inspect older release years / potential outliers
df[df["release_year"] < 1950][["title", "release_year", "listed_in"]]

,title,release_year,listed_in
1331,Five Came Back: The Reference Films,1945,TV Shows
4250,Pioneers: First Women Filmmakers*,1925,TV Shows
7219,Know Your Enemy - Japan,1945,"Classic Movies, Documentaries"
7294,Let There Be Light,1946,"Classic Movies, Documentaries"
7575,Nazi Concentration Camps,1945,"Classic Movies, Documentaries"
7743,Pioneers of African-American Cinema,1946,TV Shows
7790,Prelude to War,1942,"Classic Movies, Documentaries"
7930,San Pietro,1945,"Classic Movies, Documentaries"
8205,The Battle of Midway,1942,"Classic Movies, Documentaries"
8419,The Memphis Belle: A Story of a\nFlying Fortress,1944,"Classic Movies, Documentaries"
8436,The Negro Soldier,1944,"Classic Movies, Documentaries"
8587,Thunderbolt,1947,"Classic Movies, Documentaries"
8640,Tunisian Victory,1944,"Classic Movies, Documentaries"
8660,Undercover: How to Operate Behind Enemy Lines,1943,"Classic Movies, Documentaries"
8739,Why We Fight: The Battle of Russia,1943,Documentaries
8763,WWII: Report from the Aleutians,1943,Documentaries

In [ ]:
# Export clean dataset to Excel and CSV
df.to_excel("netflix_titles_cleaned.xlsx", index=False)
df.to_csv("netflix_titles_cleaned.csv", index=False)